---
# file: roles/common/tasks/main.yml

- name: be sure timezone is set to 'Asia/Tokyo'
  command: timedatectl set-timezone 'Asia/Tokyo'
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 7

- name: be sure locale is set to 'ja_JP.UTF-8'
  command: localectl set-locale LANG='ja_JP.UTF-8'
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 7

- name: be sure yum is updated
  yum: name=* state=latest

- name: be sure common packages are installed
  yum: name={{ item }} state=latest
  with_items:
    - chrony
    - telnet
    - nc
    - rsync
    - wget
    - dstat
    - sysstat
    - tree
    - lsof
    - git
    - mlocate
    - psmisc
    - net-tools
  notify: update updatedb

- name: be sure chronyd is enabled and running
  service: name=chronyd enabled=yes state=started
